language: php
php:
  - 5.5
  - 5.6
mysql:
  database: activecollab_memories_test
  username: root
  encoding: utf8mb4
install: composer install --dev
before_script:
  # create the database
  - mysql -e 'create database activecollab_memories_test'
script: phpunit -c test/phpunit.xml