language: php
php:
  - 7.1
mysql:
  database: activecollab_memories_test
  username: root
  encoding: utf8mb4
install: composer install --dev
before_script:
  # create the database
  - mysql -e 'create database activecollab_memories_test'
script: vendor/bin/phpunit
